"""baseline reset 5am

Revision ID: e9a66f38da10
Revises: 
Create Date: 2026-07-31 10:26:53.461625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a66f38da10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clases',
    sa.Column('id_curso_grupo', sa.String(length=50), nullable=False),
    sa.Column('id_docente', sa.String(length=100), nullable=False),
    sa.Column('asignatura', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.String(length=10), nullable=False),
    sa.Column('numero_estudiantes', sa.Integer(), nullable=False),
    sa.Column('puntaje_claridad', sa.Float(), nullable=False),
    sa.Column('puntaje_metodologia', sa.Float(), nullable=False),
    sa.Column('puntaje_evaluacion', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('tendencia_desempeno', sa.String(length=10), nullable=False),
    sa.Column('clases_pactadas', sa.Integer(), nullable=False),
    sa.Column('clases_dictadas', sa.Integer(), nullable=False),
    sa.Column('dias_clase', sa.String(length=100), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('franja_horaria', sa.String(length=10), nullable=False),
    sa.Column('promedio_asistencias_estudiantes', sa.Float(), nullable=False),
    sa.Column('numero_estudiantes_aprobaron', sa.Integer(), nullable=False),
    sa.Column('numero_estudiantes_perdieron', sa.Integer(), nullable=False),
    sa.Column('numero_estudiantes_desistieron', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_curso_grupo')
    )
    op.create_index(op.f('ix_clases_asignatura'), 'clases', ['asignatura'], unique=False)
    op.create_index(op.f('ix_clases_id_curso_grupo'), 'clases', ['id_curso_grupo'], unique=False)
    op.create_index(op.f('ix_clases_id_docente'), 'clases', ['id_docente'], unique=False)
    op.create_index(op.f('ix_clases_semestre'), 'clases', ['semestre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clases_semestre'), table_name='clases')
    op.drop_index(op.f('ix_clases_id_docente'), table_name='clases')
    op.drop_index(op.f('ix_clases_id_curso_grupo'), table_name='clases')
    op.drop_index(op.f('ix_clases_asignatura'), table_name='clases')
    op.drop_table('clases')
    # ### end Alembic commands ###
