services:
    fastapi:
        userns_mode: "keep-id"
        build:
            context: ..
            dockerfile: Dockerfile
            privileged: false
        environment:
            GUNICORN_PORT: 9233
        ports:
            - "9233:9233"
        env_file:
            - db.env
        volumes:
            - type: bind
              source: ../..
              target: /workspaces
              bind:
                  create_host_path: true
                  propagation: rshared
                  selinux: z
              read_only: false
              consistency: cached
        command: sleep infinity
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2GB
    postgres:
        image: postgres:17
        restart: unless-stopped
        stop_grace_period: 1m
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - db.env
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2GB
volumes:
    postgres_data:
