name: Trigger auto deployment for analitica-educativa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/analitica-educativa-AutoDeployTrigger-54104fda-5742-40a3-ab88-ebe85472f516.yml'

  # Allow manual trigger 
  workflow_dispatch:      

permissions: 
  id-token: write #This is required for requesting the OIDC JWT Token
  contents: read #Required when GH token is used to authenticate with private repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ANALITICAEDUCATIVA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ANALITICAEDUCATIVA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ANALITICAEDUCATIVA_AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: techtailors.azurecr.io
          registryUsername: ${{ secrets.ANALITICAEDUCATIVA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANALITICAEDUCATIVA_REGISTRY_PASSWORD }}
          containerAppName: analitica-educativa
          resourceGroup: sic-education-analytics
          imageToBuild: techtailors.azurecr.io/analitica-educativa:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


